<?php
return $lang = [
    'telegram_bot' => [
        'ru' => [
            'You are welcome! Send your phone number for ordering information.' => 'Рады приветствовать Вас! Пришлите свой номер телефона, для информации о заказах.',
            'You are already registered with a number %number%' => 'Вы уже зарегистрированы с номером %number%',
            'Send number' => 'Отправить номер',
            'You are deceiving me %number% is not your number' => 'Вы меня обманываете %number% - не Ваш номер',
            'Thank you, you will now receive information about orders.' => 'Благодарю, Вы теперь будете получать информацию о заказах.',
            'Something went wrong( Please try again later' => 'Что-то пошло не так( Повторите попытку позже',
            'Here\'s what I can do:' => 'Вот что я умею:',
            'Please send your number by clicking on the button <b>Send number</b> under the input line' => 'Пожалуйста, отправьте свой номер нажав на кнопку <b>Отправить номер</b> под строкой ввода',
            'I do not understand' => 'Я вас не понимаю',
            'My orders' => 'Мои заказы',
            'You have %count% orders' => "У Вас %count% заказов",
            "<b>Order from %date%:</b>\nOrder number: %order_code%,\nEstimated readiness date: %order_plan_of_production%,\nOrder details: <a href='https://q.ifurn.pro/v/p/%order_code%'>More</a>\n\n" =>
                "<b>Заказ от %date%:</b>\nНомер заказа: %order_code%,\nОрентировочная дата готовности: %order_plan_of_production%,\nПолная информация о заказе: <a href='https://q.ifurn.pro/v/p/%order_code%'>Подробнее</a>\n \n",
            'Select order status:' => 'Выберите статус заказов:',
            'Confirmed' => 'Подтвержден',
            'Confirmed for production' => 'Подтвержден в производство',
            'In work' => 'В работе',
            'Completed' => 'Выполнен',
            'Ready for shipment' => 'Готов к отгрузке',
            'Shipped' => 'Отгружен',
            'Canceled' => 'Отменен',
            'Follow this link' => 'Перейдите по ссылке',
            'Information about order' => 'Информация о заказе',
            'Languages' => 'Язык',
            "Select Language:" => 'Выберите язык:',
            "Ukraine" => 'Украинский',
            "English" => 'Английский',
            "russian" => 'русский',
            "Thank you, now I will communicate with you in English" => 'Спасибо, теперь я буду общаться с вами на русском',
        ],
        'ua' => [
            'You are welcome! Send your phone number for ordering information.' => 'Раді вітати Вас! Надішліть свій номер телефону, для інформації про замовлення.',
            'You are already registered with a number %number%' => 'Ви вже зареєстровані з номером %number%',
            'Send number' => 'Надіслати номер',
            'You are deceiving me %number% is not your number' => 'Ви мене обманюєте %number% - не Ваш номер',
            'Thank you, you will now receive information about orders.' => 'Дякую, Ви тепер отримуватимете інформацію про замовлення.',
            'Something went wrong( Please try again later' => 'Щось пішло не так( Повторіть спробу пізніше',
            'Here\'s what I can do:' => 'Ось що я можу:',
            'Please send your number by clicking on the button <b>Send number</b> under the input line' => 'Будь ласка, відправте свій номер, натиснувши на кнопку <b>Надіслати номер</b> під рядком введення',
            'I do not understand' => 'Я вас не розумію',
            'My orders' => 'Мої замовлення',
            'You have %count% orders' => 'У вас %count% замовлень',
            "<b>Order from %date%:</b>\nOrder number: %order_code%,\nEstimated readiness date: %order_plan_of_production%,\nOrder details: <a href='https://q.ifurn.pro/v/p/%order_code%'>More</a>\n\n" =>
                "<b>Замовлення від %date%:</b>\nНомер замовлення: %order_code%,\nПриблизна дата готовності: %order_plan_of_production%,\nПовна інформація про замовлення: <a href='https://q.ifurn.pro/v/p/%order_code%'>Докладніше</a>\n\n",
            'Select order status:' => 'Оберіть статус замовлень:',
            'Confirmed' => 'Підтверджено',
            'Confirmed for production' => 'Підтверджено у виробництво',
            'In work' => 'В роботі',
            'Completed' => 'Виконаний',
            'Ready for shipment' => 'Готовий до відвантаження',
            'Shipped' => 'Відвантажений',
            'Canceled' => 'Скасовано',
            'Follow this link' => 'Перейдіть за посиланням',
            'Information about order' => 'Інформація про замовлення',
            'Languages' => 'Мова',
            "Select Language:" => 'Оберіть мову:',
            "Ukraine" => 'Солов\'їна',
            "English" => 'Англійська',
            "russian" => 'російська',
            "Thank you, now I will communicate with you in English" => 'Дякую, тепер я буду спілкуватися з вами українською',

       ]
    ],
    'viber_bot' => [
        'ru' => [
            'We are glad to welcome you! Please provide your phone number so we can identify you.' => 'Рады Вас приветствовать! Пожалуйста, отправьте свой номер телефона, что бы мы могли Вас идентифицировать.',
            '<b>Send number</b>' => '<b>Отправить номер телефона</b>',
            'Select order status:' => 'Выберите статус заказов:',
            'Confirmed' => 'Подтвержден',
            'Confirmed for production' => 'Подтвержден в производство',
            'In work' => 'В работе',
            'Completed' => 'Выполнен',
            'Ready for shipment' => 'Готов к отгрузке',
            'Shipped' => 'Отгружен',
            'Canceled' => 'Отменен',
            'You are already registered with a number %number%' => 'Вы уже зарегистрированы с номером %number%',
            "*Order from* %date%:\nOrder number: %order_code%,\nEstimated readiness date: %order_plan_of_production%,\nOrder details: https://q.ifurn.pro/v/p/%order_code%\n\n" =>
                "*Заказ от* %date%:\nНомер заказа: %order_code%,\nОрентировочная дата готовности: %order_plan_of_production%,\nПолная информация о заказе: https://q.ifurn.pro/v/p/%order_code%\n\n",
            '<b>Orders list</b>' => "<b>Список заказов</b>",
            '<b>Set Language</b>' => "<b>Изменить язык</b>",
            "Select Language:" => 'Выберите язык:',
            'I don\'t understand you' => "Я Вас не понимаю",
            'You are deceiving me %number% is not your number' => 'Вы меня обманываете %number% - не Ваш номер',
            'Thank you, you will now receive information about orders.' => 'Благодарю, Вы теперь будете получать информацию о заказах.',
            'My orders' => 'Мои заказы',
            'You have %count% orders' => "У Вас %count% заказов\n",
            'Follow this link' => 'Перейдите по ссылке',
            'Information about order' => 'Информация о заказе',
            "Thank you, now I will communicate with you in English" => 'Спасибо, теперь я буду общаться с вами на русском',
        ],
        'ua' => [
            'We are glad to welcome you! Please provide your phone number so we can identify you.' => 'Раді Вас вітати! Будь ласка, надішліть свій номер телефону, щоб ми могли Вас ідентифікувати.',
            '<b>Send number</b>' => '<b>Надіслати номер телефону</b>',
            'Select order status:' => 'Виберіть статус замовлень:',
            'Confirmed' => 'Підтверджено',
            'Confirmed for production' => 'Підтверджено у виробництво',
            'In work' => 'В роботі',
            'Completed' => 'Виконаний',
            'Ready for shipment' => 'Готовий до відвантаження',
            'Shipped' => 'Відвантажений',
            'Canceled' => 'Скасовано',
            'Follow this link' => 'Перейдіть за посиланням',
            'Information about order' => 'Інформація про замовлення',
            'You are already registered with a number %number%' => 'Ви вже зареєстровані з номером %number%',
            'You are deceiving me %number% is not your number' => 'Ви мене обманюєте %number% - не Ваш номер',
            'Thank you, you will now receive information about orders.' => 'Дякую, Ви тепер отримуватимете інформацію про замовлення.',

            "*Order from* %date%:\nOrder number: %order_code%,\nEstimated readiness date: %order_plan_of_production%,\nOrder details: https://q.ifurn.pro/v/p/%order_code%\n\n" =>
                "*Замовлення від* %date%:\nНомер замовлення: %order_code%,\nПриблизна дата готовності: %order_plan_of_production%,\nПовна інформація про замовлення: https://q.ifurn.pro/v/p/%order_code%\n\n",
            '<b>Orders list</b>' => "<b>Перелік замовлень</b>",
            '<b>Set Language</b>' => "<b>Змінити мову</b>",
            "Select Language:" => 'Оберіть мову:',
            'I don\'t understand you' => "Я вас не розумію",
            'My orders' => 'Мої замовлення',
            'You have %count% orders' => "У вас %count% замовлень",
            "Thank you, now I will communicate with you in English" => 'Дякую, тепер я спілкуватимуся з вами українською',
        ],
    ]
];